#金蝶erp配置文件
# 金蝶云星空 WebAPI 配置文件

# 1. 服务地址 (ServerUrl)
serverUrl=https://kd.havitgo.com/k3cloud/

# 2. 数据中心ID (dcID)
dcID=68c13132409460

# 3. 用户名 (UserName)
# 参数名是 UserName
userName=管理账号

# 4. 密码 (Password)
pwd=68c13132409460

# 5. 第三方应用ID (AppId)
appId=327246_X30qwZkKQol51eyuwfQL7+8K3LS/1pOv

# 6. 第三方应用密钥 (AppSecret)
appSecret=4c56306cf29d4e54900d57a86e3abc17

# 7. 语言ID (LCID)，默认为中文
lCID=2052